"use client";
import { useRef, useState, useTransition } from "react";
import { Plus, X } from "lucide-react";
import { saveEntry } from "@/actions/entry-actions";

export function EntryForm() {
  const dialog = useRef<HTMLDialogElement>(null); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  function submit(formData: FormData) { const clockIn = String(formData.get("clockInLocal")); const clockOut = String(formData.get("clockOutLocal")); formData.set("clockIn", new Date(clockIn).toISOString()); formData.set("clockOut", new Date(clockOut).toISOString()); startTransition(async () => { const result = await saveEntry(formData); setMessage(result.message ?? ""); if (result.ok) dialog.current?.close(); }); }
  return <><button className="button-primary" onClick={() => dialog.current?.showModal()}><Plus aria-hidden/>הוספת דיווח</button><dialog ref={dialog} className="m-auto w-[calc(100%-2rem)] max-w-lg rounded-[28px] border-0 bg-white p-0 shadow-2xl backdrop:bg-black/50"><form action={submit} className="grid gap-5 p-5 sm:p-7"><header className="flex items-center justify-between"><div><h2 className="text-2xl font-extrabold">הוספת דיווח</h2><p className="muted text-sm">השעות יישמרו לפי אזור הזמן שלך</p></div><button type="button" aria-label="סגירת החלון" className="grid size-11 place-items-center rounded-full bg-[var(--background)]" onClick={() => dialog.current?.close()}><X aria-hidden/></button></header><div className="grid grid-cols-2 gap-3"><Field label="כניסה" name="clockInLocal" type="datetime-local" required/><Field label="יציאה" name="clockOutLocal" type="datetime-local" required/></div><Field label="הערה (לא חובה)" name="note"/><Field label="סיבת הדיווח" name="reason" required/>{message && <p role="status" className="text-sm text-[var(--error)]">{message}</p>}<div className="flex gap-3"><button className="button-primary flex-1" disabled={pending}>{pending ? "שומר..." : "שמירת דיווח"}</button><button type="button" className="button-secondary" onClick={() => dialog.current?.close()}>ביטול</button></div></form></dialog></>;
}
function Field(props: React.InputHTMLAttributes<HTMLInputElement> & {label:string}) { const { label, ...inputProps } = props; const id = String(inputProps.name); return <div className="field"><label htmlFor={id}>{label}</label><input id={id} className="input" {...inputProps}/></div>; }
