"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { normalizeUsername, usernameSchema } from "@/lib/validation/schemas";
import { isDemoMode } from "@/lib/demo";

async function auth() { const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error("not_authenticated"); return {supabase,user}; }
export async function saveProfile(formData:FormData) { if(isDemoMode()){revalidatePath("/app/settings");return;} const {supabase,user}=await auth(); const username=usernameSchema.safeParse(String(formData.get("username")??"")); if(!username.success) return; await supabase.from("profiles").update({username:username.data,normalized_username:normalizeUsername(username.data),full_name:String(formData.get("fullName")??"")||null,timezone:String(formData.get("timezone")??"Asia/Jerusalem")}).eq("id",user.id); revalidatePath("/app/settings"); }
export async function addLeave(formData:FormData) { if(isDemoMode()){revalidatePath("/app/settings");return;} const {supabase,user}=await auth(); await supabase.from("leave_entries").insert({user_id:user.id,leave_type:String(formData.get("leaveType")),start_date:String(formData.get("startDate")),end_date:String(formData.get("endDate")),partial_minutes:formData.get("partialMinutes")?Number(formData.get("partialMinutes")):null,status:"approved",note:String(formData.get("note")??"")||null}); revalidatePath("/app/settings"); }
export async function addException(formData:FormData) { if(isDemoMode()){revalidatePath("/app/settings");return;} const {supabase,user}=await auth(); await supabase.from("calendar_exceptions").upsert({user_id:user.id,exception_date:String(formData.get("date")),exception_type:String(formData.get("type")),name:String(formData.get("name")),target_minutes:formData.get("targetMinutes")?Number(formData.get("targetMinutes")):null,note:String(formData.get("note")??"")||null},{onConflict:"user_id,exception_date"}); revalidatePath("/app/settings"); }
export async function saveReminders(formData:FormData) { if(isDemoMode()){revalidatePath("/app/settings");return;} const {supabase,user}=await auth(); await supabase.from("reminder_settings").upsert([{user_id:user.id,reminder_type:"clock_in",enabled:formData.get("clockInEnabled")==="on",local_time:String(formData.get("clockInTime")),weekdays:[0,1,2,3,4],timezone:"Asia/Jerusalem"},{user_id:user.id,reminder_type:"clock_out",enabled:formData.get("clockOutEnabled")==="on",local_time:String(formData.get("clockOutTime")),weekdays:[0,1,2,3,4],timezone:"Asia/Jerusalem"}],{onConflict:"user_id,reminder_type"}); revalidatePath("/app/settings"); }
