"use client";
import { useState } from "react";
import { BriefcaseBusiness, ChevronLeft, ChevronRight, Coins, UserRound } from "lucide-react";
import { completeOnboarding } from "@/actions/onboarding-actions";
const steps = ["פרופיל", "שגרת העבודה", "הגדרת שכר", "חופשות ותזכורות"];

export function OnboardingWizard({ initialUsername }: { initialUsername: string }) {
  const [step, setStep] = useState(0); const [mode, setMode] = useState("hidden");
  return <form action={completeOnboarding} className="grid gap-5"><ol className="flex gap-2" aria-label="שלבי ההגדרה">{steps.map((label, index) => <li key={label} className={`h-2 flex-1 rounded-full ${index <= step ? "bg-[var(--primary)]" : "bg-[var(--surface-muted)]"}`}><span className="sr-only">{label}{index === step ? " – השלב הנוכחי" : ""}</span></li>)}</ol>
    <div className="min-h-[350px]"><div hidden={step !== 0}><Step title="נעים להכיר" subtitle="הפרטים שיעזרו לנו להתאים את ClockIn אליך" icon={UserRound}><Field label="שם משתמש" name="username" defaultValue={initialUsername} required/><Field label="שם מלא (לא חובה)" name="fullName" autoComplete="name"/><label className="field"><span>אזור זמן</span><select className="input" name="timezone" defaultValue="Asia/Jerusalem"><option value="Asia/Jerusalem">ישראל – ירושלים</option><option value="Europe/London">אירופה – לונדון</option><option value="America/New_York">אמריקה – ניו יורק</option></select></label></Step></div>
    <div hidden={step !== 1}><Step title="מתי עובדים?" subtitle="אפשר לשנות כל יום בנפרד בהגדרות" icon={BriefcaseBusiness}><div className="rounded-2xl bg-[var(--primary-soft)] p-4"><b>ראשון עד חמישי</b><p className="muted text-sm">שישי ושבת מוגדרים כימי מנוחה</p></div><div className="grid grid-cols-2 gap-3"><Field label="שעת התחלה" name="startTime" type="time" defaultValue="08:30"/><Field label="שעת סיום" name="endTime" type="time" defaultValue="17:00"/></div><Field label="יעד יומי בדקות" name="targetMinutes" type="number" inputMode="numeric" defaultValue="510"/></Step></div>
    <div hidden={step !== 2}><Step title="איך להציג שכר?" subtitle="כל הסכומים מסומנים כהערכה בלבד" icon={Coins}><div className="grid gap-2">{[["hidden","לא להציג שכר"],["hourly","שכר שעתי"],["global","שכר גלובלי"]].map(([value,label]) => <label key={value} className={`flex min-h-14 items-center gap-3 rounded-2xl border p-3 ${mode === value ? "border-[var(--primary)] bg-[var(--primary-soft)]" : "border-[var(--border-soft)]"}`}><input type="radio" name="compensationMode" value={value} checked={mode === value} onChange={() => setMode(value)}/><b>{label}</b></label>)}</div>{mode === "hourly" && <Field label="תעריף לשעה (₪)" name="hourlyRate" type="number" inputMode="decimal"/>}{mode === "global" && <Field label="שכר חודשי (₪)" name="monthlySalary" type="number" inputMode="decimal"/>}</Step></div>
    <div hidden={step !== 3}><Step title="כמעט סיימנו" subtitle="יתרות פתיחה ותזכורות עדינות" icon={BriefcaseBusiness}><div className="grid grid-cols-2 gap-3"><Field label="יתרת חופשה בימים" name="vacationBalance" type="number" inputMode="decimal" defaultValue="0"/><Field label="יתרת מחלה בימים" name="sickBalance" type="number" inputMode="decimal" defaultValue="0"/></div><label className="flex min-h-14 items-center justify-between rounded-2xl bg-[var(--background)] p-4"><span><b>הפעלת תזכורות</b><small className="muted block">אפשר לשנות הרשאה בהמשך</small></span><input type="checkbox" name="notifications" className="size-5"/></label><div className="grid grid-cols-2 gap-3"><Field label="תזכורת כניסה" name="clockInReminder" type="time" defaultValue="08:25"/><Field label="תזכורת יציאה" name="clockOutReminder" type="time" defaultValue="17:05"/></div></Step></div></div>
    <div className="flex gap-3">{step > 0 && <button type="button" onClick={() => setStep(step-1)} className="button-secondary flex-1"><ChevronRight aria-hidden/>הקודם</button>}{step < steps.length-1 ? <button type="button" onClick={() => setStep(step+1)} className="button-primary flex-1">המשך<ChevronLeft aria-hidden/></button> : <button className="button-primary flex-1">סיום והתחלה<ChevronLeft aria-hidden/></button>}</div></form>;
}
function Step({ title, subtitle, icon: Icon, children }: { title:string; subtitle:string; icon: typeof UserRound; children:React.ReactNode }) { return <section className="grid gap-5"><div className="pt-2"><span className="mb-4 grid size-12 place-items-center rounded-2xl bg-[var(--primary-soft)] text-[var(--primary)]"><Icon aria-hidden/></span><h2 className="text-2xl font-extrabold">{title}</h2><p className="muted mt-1">{subtitle}</p></div>{children}</section>; }
function Field(props: React.InputHTMLAttributes<HTMLInputElement> & { label:string }) { const { label, ...rest } = props; const id = `field-${rest.name}`; return <div className="field"><label htmlFor={id}>{label}</label><input id={id} className="input" {...rest}/></div>; }
